In [1]:
import pandas as pd

In [8]:
SFRcounty=pd.read_csv('http://files.zillowstatic.com/research/public/County/County_Zhvi_SingleFamilyResidence.csv')
SFRcounty.head(20)

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,1996-04,1996-05,1996-06,...,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01
0,3101,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,6,37,1,164000.0,164000.0,163700.0,...,584700,587800,590200,592400,596200,601500,606400,611700,616600,619500
1,139,Cook,IL,Chicago,17,31,2,144400.0,144000.0,143500.0,...,228200,228400,228000,227500,227300,227800,228600,229100,229200,229800
2,2402,Maricopa,AZ,Phoenix,4,13,3,112300.0,112500.0,113000.0,...,254600,256300,258200,259700,261200,263200,265300,266600,267200,267900
3,2841,San Diego,CA,San Diego,6,73,4,178500.0,177900.0,177400.0,...,573100,580700,586800,590400,593300,595800,598700,602100,606300,610500
4,1286,Orange,CA,Los Angeles-Long Beach-Anaheim,6,59,5,218100.0,218200.0,218000.0,...,724900,729400,733000,735100,736700,738700,741500,744900,750300,756100
5,581,Kings,NY,New York,36,47,6,173000.0,173400.0,174000.0,...,739900,744000,746800,748900,751800,757100,760800,761600,764100,768700
6,2964,Miami-Dade,FL,Miami-Fort Lauderdale,12,86,7,116900.0,116800.0,116500.0,...,308500,310600,313400,316600,319900,323100,325700,327200,327600,328100
7,978,Dallas,TX,Dallas-Fort Worth,48,113,8,NaN,NaN,NaN,...,177100,178100,178500,178200,179000,181500,184300,186200,187500,188500
8,1347,Queens,NY,New York,36,81,9,169100.0,167900.0,167200.0,...,650900,655500,656700,658100,662500,668400,670700,669100,667200,668500
9,2832,Riverside,CA,Riverside,6,65,10,128100.0,127400.0,126600.0,...,347000,349800,352900,355400,357900,361000,364200,365200,365800,367500
10,3250,San Bernardino,CA,Riverside,6,71,11,104100.0,103900.0,103800.0,...,310900,313200,315900,318200,320000,321300,322700,325400,328400,330300
11,445,Clark,NV,Las Vegas,32,3,12,135200.0,134600.0,133800.0,...,244800,247700,250300,252500,255100,258700,262300,265400,267300,268500
12,207,King,WA,Seattle,53,33,13,174900.0,174600.0,174500.0,...,609600,624800,635500,639700,641900,646100,653700,661500,667100,671400
13,2049,Tarrant,TX,Dallas-Fort Worth,48,439,14,NaN,NaN,NaN,...,184100,185700,187200,188100,189200,190400,191700,193300,194500,195000
14,3136,Santa Clara,CA,San Jose,6,85,15,273200.0,273700.0,274600.0,...,1138100,1153300,1167200,1182500,1199800,1222200,1253300,1289400,1325800,1350700
15,1561,Broward,FL,Miami-Fort Lauderdale,12,11,16,115300.0,115000.0,114800.0,...,300800,304100,305600,306000,307400,310000,313500,315900,316700,317200
16,2452,New York,NY,New York,36,61,17,NaN,NaN,1685200.0,...,8675400,8575000,8569400,8543500,8394000,8292900,8307000,8383000,8445600,8496900
17,3175,Philadelphia,PA,Philadelphia,42,101,18,82400.0,82700.0,82900.0,...,194800,196400,198000,199500,201300,202900,204200,205800,207500,208900
18,1510,Alameda,CA,San Francisco,6,1,19,204600.0,204500.0,204400.0,...,840300,844200,848500,851900,855900,863500,872500,884100,899100,911000
19,2801,Middlesex,MA,Boston,25,17,20,185200.0,185400.0,185400.0,...,518400,523400,526700,527900,530300,534700,539500,543500,545800,546400

In [9]:
sqft=pd.read_csv('http://files.zillowstatic.com/research/public/County/County_MedianValuePerSqft_AllHomes.csv')
sqft.head(20)

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,1996-04,1996-05,1996-06,...,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01
0,3101,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,6,37,1,113.0,113.0,113.0,...,394,397,398,400,402,406,409,413,417,419
1,139,Cook,IL,Chicago,17,31,2,103.0,103.0,103.0,...,165,164,164,164,164,165,165,165,166,166
2,2402,Maricopa,AZ,Phoenix,4,13,3,62.0,62.0,62.0,...,141,142,143,144,145,146,148,149,149,150
3,2841,San Diego,CA,San Diego,6,73,4,105.0,105.0,105.0,...,342,346,349,351,352,354,356,358,361,364
4,1286,Orange,CA,Los Angeles-Long Beach-Anaheim,6,59,5,122.0,122.0,121.0,...,410,413,416,417,419,420,422,424,428,431
5,2964,Miami-Dade,FL,Miami-Fort Lauderdale,12,86,6,70.0,70.0,69.0,...,184,185,186,188,189,191,194,195,195,194
6,978,Dallas,TX,Dallas-Fort Worth,48,113,7,NaN,NaN,NaN,...,107,108,109,110,110,111,112,113,114,114
7,1347,Queens,NY,New York,36,81,8,121.0,121.0,121.0,...,440,444,444,445,449,453,455,456,457,459
8,2832,Riverside,CA,Riverside,6,65,9,69.0,69.0,68.0,...,184,186,188,189,190,192,194,194,195,196
9,3250,San Bernardino,CA,Riverside,6,71,10,67.0,67.0,67.0,...,200,202,204,205,207,208,209,210,212,213
10,445,Clark,NV,Las Vegas,32,3,11,75.0,75.0,75.0,...,130,132,134,135,136,139,141,142,143,145
11,207,King,WA,Seattle,53,33,12,99.0,98.0,99.0,...,329,336,342,345,347,351,355,360,363,365
12,791,Wayne,MI,Detroit,26,163,13,NaN,73.0,74.0,...,69,70,70,71,72,73,74,74,74,74
13,2049,Tarrant,TX,Dallas-Fort Worth,48,439,14,NaN,NaN,NaN,...,102,103,103,104,105,106,106,107,108,108
14,3136,Santa Clara,CA,San Jose,6,85,15,160.0,160.0,161.0,...,662,670,676,682,691,701,717,737,756,767
15,1561,Broward,FL,Miami-Fort Lauderdale,12,11,16,63.0,63.0,63.0,...,160,161,162,163,164,165,167,169,169,169
16,2452,New York,NY,New York,36,61,17,NaN,NaN,183.0,...,1454,1455,1459,1462,1461,1457,1455,1456,1455,1453
17,3175,Philadelphia,PA,Philadelphia,42,101,18,40.0,40.0,39.0,...,103,104,104,105,106,107,108,110,111,112
18,1510,Alameda,CA,San Francisco,6,1,19,131.0,131.0,131.0,...,520,523,527,529,532,537,543,551,560,568
19,2801,Middlesex,MA,Boston,25,17,20,107.0,107.0,108.0,...,294,296,299,300,302,304,306,307,309,309

In [10]:
cenhousing=pd.read_csv('https://www2.census.gov/programs-surveys/popest/datasets/2000-2010/intercensal/housing/h')

HTTPError: HTTP Error 404: Not Found